### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by sukrutrao** [GoodDeeds/interval-domain-abstract-interpreter#9]
Set up CI for automated builds

**Comment by sukrutrao** [comment]
Ref: [83ca6e](https://github.com/GoodDeeds/interval-domain-abstract-interpreter/commit/83ca6ec8b1884245a4ee0cca8f5d4a035c5220fb)

I figured out the minisat part. But then the README instructions also need to be updated (later) as this is not mentioned.

Can you add the necessary prerequisites?

@prateekkumarweb

**Comment by prateekkumarweb** [comment]
@GoodDeeds Why do you have to say only ci branch? Doesn't it take only the pushed commit?

**Comment by sukrutrao** [comment]
Can be removed now I think, I was experimenting.

**Comment by prateekkumarweb** [comment]
@GoodDeeds Build succeeded. I think we should cache the build files in `cbmc/src` in travis.
